server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${HOME}/livecoding-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
